name: meuapp
description: "A new Flutter project."
publish_to: 'none' # Não publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0-106.0.dev

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
